job_portal_admin_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JobPortalAdminBundle:Default:index }

_login_index:
    pattern: /login
    defaults: { _controller: JobPortalAdminBundle:Login:index }
    

_logout_index:
    pattern: /logout
    defaults: { _controller: JobPortalAdminBundle:Logout:index }

_dahboard_index:
    pattern: /dashboard
    defaults: { _controller: JobPortalAdminBundle:Dashboard:index }
#routing start by shibu
_index:
    pattern:     /categories
    defaults: { _controller: JobPortalAdminBundle:Categories:index }
    
_category_add:
    pattern:     /addCategory
    defaults: { _controller: JobPortalAdminBundle:Categories:add }

_category_edit:
    pattern:     /editCategory
    defaults: { _controller: JobPortalAdminBundle:Categories:edit }    
    
_category_delete:
    pattern:     /deleteCategory
    defaults: { _controller: JobPortalAdminBundle:Categories:delete }
    
_admin_profile_update:
    pattern: /adminUpdate
    defaults: { _controller: JobPortalAdminBundle:Dashboard:adminUpdate }
    
_admin_changePassword:
    pattern: /adminChangePassword
    defaults: { _controller: JobPortalAdminBundle:Dashboard:adminChangePassword }
    
_forget_password:
    pattern: /forgetPassword
    defaults: { _controller: JobPortalAdminBundle:Login:forgetPassword }
    
_change_forget_password:
    pattern: /changeForgetPassword
    defaults: { _controller: JobPortalAdminBundle:Login:changeForgetPassword }
