job_portal_admin_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JobPortalAdminBundle:Default:index }

_login_index:
    pattern: /login
    defaults: { _controller: JobPortalAdminBundle:Login:index }
    

_logout_index:
    pattern: /logout
    defaults: { _controller: JobPortalAdminBundle:Logout:index }

_dahboard_index:
    pattern: /dashboard
    defaults: { _controller: JobPortalAdminBundle:Dashboard:index }
#routing start by shibu
_category_index:
    pattern:     /categories
    defaults: { _controller: JobPortalAdminBundle:Categories:index }
    
_category_add:
    pattern:     /addCategory
    defaults: { _controller: JobPortalAdminBundle:Categories:add }

_category_edit:
    pattern:     /editCategory/{id}
    defaults: { _controller: JobPortalAdminBundle:Categories:edit }    
    
_category_delete:
    pattern:     /deleteCategory
    defaults: { _controller: JobPortalAdminBundle:Categories:delete }

_admin_profile_update:
    pattern: /adminUpdate
    defaults: { _controller: JobPortalAdminBundle:Dashboard:adminUpdate }
    
_admin_changePassword:
    pattern: /adminChangePassword
    defaults: { _controller: JobPortalAdminBundle:Dashboard:adminChangePassword }


_status_update:
    path:     /statusUpdate
    defaults: { _controller: JobPortalAdminBundle:Common:statusUpdate }

_delete_update:
    path:     /deleteUpdate/{id}/{table}/{route}
    defaults: { _controller: JobPortalAdminBundle:Common:deleteUpdate }

_question_index:
    path:     /viewQuestion
    defaults: { _controller: JobPortalAdminBundle:Questions:index }
_question_add:
    path:     /addQuestion
    defaults: { _controller: JobPortalAdminBundle:Questions:add }

_answer_index:
    path:     /index
    defaults: { _controller: JobPortalAdminBundle:Answers:index }
    
_ajax_quesion_view:
    path: /ajaxQuestionView
    defaults: { _controller: JobPortalAdminBundle:Questions:ajaxQuestionView }
    
_details_quesion_view:
    path: /detailsQuestionView
    defaults: { _controller: JobPortalAdminBundle:Questions:detailsQuestionView }

_update_quesion_view:
    path: /updateQuestion
    defaults: { _controller: JobPortalAdminBundle:Questions:updateQuestion }
_admin_profile_update:
    pattern: /adminUpdate
    defaults: { _controller: JobPortalAdminBundle:Dashboard:adminUpdate }
    
_admin_changePassword:
    pattern: /adminChangePassword
    defaults: { _controller: JobPortalAdminBundle:Dashboard:adminChangePassword }
    
_forget_password:
    pattern: /forgetPassword
    defaults: { _controller: JobPortalAdminBundle:Login:forgetPassword }
    
_change_forget_password:
    pattern: /changeForgetPassword
    defaults: { _controller: JobPortalAdminBundle:Login:changeForgetPassword }

    
_forget_password:
    pattern: /forgetPassword
    defaults: { _controller: JobPortalAdminBundle:Login:forgetPassword }
    
_change_forget_password:
    pattern: /changeForgetPassword
    defaults: { _controller: JobPortalAdminBundle:Login:changeForgetPassword }

_candidate_profile_type:
    pattern: /addProfileType
    defaults: { _controller: JobPortalAdminBundle:Dashboard:addProfileType }
    
_candidate_profile_type_view:
    pattern: /viewProfileType
    defaults: { _controller: JobPortalAdminBundle:Dashboard:viewProfileType }
    
_candidate_profile_type_edit:
    pattern: /editProfileType/{id}
    defaults: { _controller: JobPortalAdminBundle:Dashboard:editProfileType }
